version: "3.9"

services:
  backend:
    build: .
    image: docs_flow_backend:latest
    container_name: docs_flow_backend_container
    command: poetry run python3 ./manage.py runserver 0.0.0.0:${DOCKER_CONTAINER_PORT}
    ports:
    - "${DOCKER_HOST_PORT}:${DOCKER_CONTAINER_PORT}"
    volumes:
      - .:/app