# Generated by Django 5.1.3 on 2024-11-26 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('relation', 'relation')], max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.project')),
            ],
        ),
        migrations.CreateModel(
            name='RelationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('snapshot', models.FilePathField(blank=True, null=True, path='D:\\projects\\docs_flow_backend\\media\\snapshots\\relation_table')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.store')),
            ],
        ),
        migrations.CreateModel(
            name='RelationTableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(blank=True, default=0)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instance.relationtablefield')),
                ('relation_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instance.relationtable')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'relation_table'), name='relation_table_field_unique_name_relation_table')],
            },
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='store_unique_name_project'),
        ),
        migrations.AddConstraint(
            model_name='relationtable',
            constraint=models.UniqueConstraint(fields=('name', 'store'), name='relation_table_unique_name_store'),
        ),
    ]
